export const settingsFields = [
    { key: 'reservation_name', type: 'text' },
    { key: 'reservation_additional_info', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'reservation_show_additional_info_link', type: 'boolean' },
    { key: 'reservation_additional_info_link_text', type: 'text', placeholders: true },
    { key: 'reservation_additional_info_link', type: 'text' },
    { key: 'reservation_details', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'reservation_details_summary_label', type: 'text' },
    { key: 'reservation_show_details_info_link', type: 'boolean' },
    { key: 'reservation_details_info_link_text', type: 'text', placeholders: true },
    { key: 'reservation_details_info_link', type: 'text' },
    { key: 'reservation_name_maxchar', type: 'number' },
    { key: 'reservation_name_minchar', type: 'number' },
    { key: 'reservation_max', type: 'number' },
    { key: 'waitlist_enabled', type: 'boolean' },
    { key: 'waitlist_auto_promote_enabled', type: 'boolean' },
    { key: 'waitlist_limit', type: 'number' },
    { key: 'waitlist_undo_enabled', type: 'boolean' },
    { key: 'waitlist_show_public', type: 'boolean', default: 0 },
    { key: 'waitlist_public_align', type: 'text', default: 'left' },
    { key: 'waitlist_overflow_enabled', type: 'boolean', default: 1 },
    { key: 'waitlist_allow_duplicate_email', type: 'boolean' },
    { key: 'waitlist_allow_duplicate_name', type: 'boolean' },
    { key: 'waitlist_duplicate_check_admin_exempt', type: 'boolean' },
    { key: 'reservation_attendees_align', type: 'text', default: 'left' },
    { key: 'waitlist_full_text', type: 'text', placeholders: true },
    { key: 'waitlist_join_button_text', type: 'text', placeholders: true },
    { key: 'waitlist_success_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'waitlist_undo_success_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'waitlist_disabled_text', type: 'text', placeholders: true },
    { key: 'reservation_enabled', type: 'boolean' },
    { key: 'reservation_undo_enabled', type: 'boolean' },
    { key: 'reservation_show_attendees_enabled', type: 'boolean' },
    { key: 'reservation_show_reservation_limit_enabled', type: 'boolean' },
    { key: 'reservation_name_blacklist_enable', type: 'boolean' },
    { key: 'reservation_name_blacklist', type: 'text' },
    { key: 'reservation_name_blacklist_unicode_enable', type: 'boolean' },
    { key: 'reservation_name_blacklist_unicode_base64', type: 'text' },
    { key: 'reservation_name_whitelist_regex_enable', type: 'boolean' },
    { key: 'reservation_name_whitelist_regex', type: 'text' },
    { key: 'reservation_email_whitelist_enable', type: 'boolean' },
    { key: 'reservation_email_whitelist', type: 'text' },
    { key: 'reservation_email_whitelist_regex_enable', type: 'boolean' },
    { key: 'reservation_email_whitelist_regex', type: 'text' },
    { key: 'reservation_allow_duplicate_email', type: 'boolean' },
    { key: 'reservation_allow_duplicate_name', type: 'boolean' },
    { key: 'reservation_duplicate_check_admin_exempt', type: 'boolean' },
    { key: 'reservation_top_image', type: 'text' },
    { key: 'reservation_top_image_alt_description', type: 'text' },
    { key: 'reservation_top_image_max_width', type: 'text' },
    { key: 'reservation_top_image_max_height', type: 'text' },
    { key: 'reservation_page_background_image', type: 'text' },
    { key: 'reservation_background_opacity', type: 'number', default: 60 },
    { key: 'reservation_background_opacity_light', type: 'number', default: null },
    { key: 'reservation_background_opacity_dark', type: 'number', default: null },
    { key: 'reservation_background_brightness_light', type: 'number', default: 100 },
    { key: 'reservation_background_brightness_dark', type: 'number', default: 100 },
    { key: 'reservation_card_opacity', type: 'number', default: 90 },
    { key: 'reservation_card_opacity_light', type: 'number', default: null },
    { key: 'reservation_card_opacity_dark', type: 'number', default: null },
    { key: 'reservation_card_color_light', type: 'color', default: '#ffffff' },
    { key: 'reservation_card_color_dark', type: 'color', default: '#1e293b' },
    { key: 'reservation_text_color_light', type: 'color', default: '#0f172a' },
    { key: 'reservation_text_color_dark', type: 'color', default: '#e2e8f0' },
    { key: 'reservation_page_favicon', type: 'text' },
    { key: 'reservation_page_title', type: 'text', placeholders: true },
    { key: 'reservation_loading_image', type: 'text' },
    { key: 'reservation_button_color_light', type: 'color', default: 'white' },
    { key: 'reservation_button_color_dark', type: 'color', default: 'white' },
    { key: 'reservation_button_backgroundcolor_light', type: 'color', default: '#2563eb' },
    { key: 'reservation_button_backgroundcolor_dark', type: 'color', default: '#2563eb' },
    { key: 'reservation_button_border_color_light', type: 'color', default: '#2563eb' },
    { key: 'reservation_button_border_color_dark', type: 'color', default: '#2563eb' },
    { key: 'reservation_undo_button_color_light', type: 'color', default: 'white' },
    { key: 'reservation_undo_button_color_dark', type: 'color', default: 'white' },
    { key: 'reservation_undo_button_backgroundcolor_light', type: 'color', default: '#2563eb' },
    { key: 'reservation_undo_button_backgroundcolor_dark', type: 'color', default: '#2563eb' },
    { key: 'reservation_undo_button_border_color_light', type: 'color', default: '#2563eb' },
    { key: 'reservation_undo_button_border_color_dark', type: 'color', default: '#2563eb' },
    { key: 'faq_button_color_light', type: 'color', default: 'white' },
    { key: 'faq_button_color_dark', type: 'color', default: 'white' },
    { key: 'faq_button_backgroundcolor_light', type: 'color', default: '#2563eb' },
    { key: 'faq_button_backgroundcolor_dark', type: 'color', default: '#2563eb' },
    { key: 'faq_button_border_color_light', type: 'color', default: '#2563eb' },
    { key: 'faq_button_border_color_dark', type: 'color', default: '#2563eb' },
    { key: 'gdpr_button_color_light', type: 'color', default: 'white' },
    { key: 'gdpr_button_color_dark', type: 'color', default: 'white' },
    { key: 'gdpr_button_backgroundcolor_light', type: 'color', default: '#2563eb' },
    { key: 'gdpr_button_backgroundcolor_dark', type: 'color', default: '#2563eb' },
    { key: 'gdpr_button_border_color_light', type: 'color', default: '#2563eb' },
    { key: 'gdpr_button_border_color_dark', type: 'color', default: '#2563eb' },
    { key: 'show_faq_button_landing_enabled', type: 'boolean' },
    { key: 'show_gdpr_button_landing_enabled', type: 'boolean' },
    { key: 'reservation_custom_css', type: 'text', component: 'textarea', hintKey: 'admin_setting_custom_css_hint' },
    { key: 'reservation_header_align', type: 'text', default: 'left' },
    { key: 'reservation_message_modal_enabled', type: 'boolean', default: 0 },
    { key: 'reservation_error_modal_enabled', type: 'boolean', default: 0 },
    { key: 'email_validation_enabled', type: 'boolean', default: 0 },
    { key: 'email_validation_admin_enabled', type: 'boolean', default: 0 },
    { key: 'email_validation_template_id', type: 'number' },
    { key: 'email_validation_ttl_minutes', type: 'number', default: 1440 },
    { key: 'email_validation_base_url', type: 'text' },
    { key: 'email_reservation_success_template_id', type: 'number' },
    { key: 'email_reservation_cancel_template_id', type: 'number' },
    { key: 'email_waitlist_promoted_template_id', type: 'number' },
    { key: 'email_waitlist_validation_success_template_id', type: 'number' },
    { key: 'email_waitlist_cancel_template_id', type: 'number' },
    { key: 'admin_reservation_notify_default', type: 'boolean', default: 0 },
    { key: 'moderator_reservation_notify_default', type: 'boolean', default: 0 },
    { key: 'reservation_show_next_event', type: 'boolean', default: 1 },
    { key: 'event_date_format', type: 'text', default: 'Y-m-d' },
    { key: 'event_time_format', type: 'text', default: 'H:i' },
    { key: 'event_timezone', type: 'text', default: 'Europe/Berlin' },
    { key: 'mail_host', type: 'text' },
    { key: 'mail_port', type: 'number' },
    { key: 'mail_username', type: 'text' },
    { key: 'mail_password', type: 'text' },
    { key: 'mail_encryption', type: 'text' },
    { key: 'mail_from_address', type: 'text' },
    { key: 'mail_global_cc', type: 'text' },
    { key: 'mail_global_bcc', type: 'text' },
    { key: 'mail_debug_domain_blacklist', type: 'text' },
    { key: 'mail_from_name', type: 'text' },
    { key: 'ical_timezone', type: 'text' },
    { key: 'ical_template', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'email_validation_rate_limit_per_hour', type: 'number', default: 5 },
    { key: 'email_validation_rate_limit_header', type: 'text', default: 'HTTP_X_FORWARDED_FOR' },
    { key: 'privacy_policy_enabled', type: 'boolean' },
    { key: 'faq_enabled', type: 'boolean' },
    { key: 'privacy_policy_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'email_validation_pending_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'reservation_success_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'reservation_undo_success_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'reservation_admin_validation_pending_text', type: 'text', component: 'textarea', hintKey: 'admin_setting_markdown_hint', placeholders: true },
    { key: 'show_project_footer', type: 'boolean', default: 1 },
    { key: 'clear_localstorage_on_logout', type: 'boolean', default: 0 },
    { key: 'login_rate_limit_attempts', type: 'number', default: 5 },
    { key: 'login_rate_limit_decay_minutes', type: 'number', default: 1 },
];