name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Get repo info
        id: vars-repo
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=REPO" >> $GITHUB_OUTPUT
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_PUSH_TOKEN }}
      - name: Build Docker image for backend
        run: docker build -t ${{ steps.vars-repo.outputs.repo }}/backend:latest ./backend
      - name: Build Docker image for frontend
        run: docker build -t ${{ steps.vars-repo.outputs.repo }}/frontend:latest ./frontend
      - name: Push Docker image for backend
        run: docker push steps.vars-repo.outputs.repo }}/backend:latest
      - name: Push Docker image for frontend
        run: docker push steps.vars-repo.outputs.repo }}/frontend:latest
